name: danish

# Endpoint parameters
host: localhost
port: 7860

# Feedback parameters
mode: feedback  # Can be "no-feedback", "feedback" and "strict-feedback"
db_path: ${dirs.final}/feedback.db
db_update_frequency: 5

# Demo sharing parameters
share: no-share  #Can be "no-share", "temporary" or "persistent"
temporary_sharing:
  username: null
  password: null
persistent_sharing:
  space_repo_id: null
  database_repo_id: null
  token_variable_name: HF_HUB_TOKEN

# User interface parameters
theme: monochrome
title: >
  RAG Bot
description: |
  En robot, der kan svare p친 alle dine sp칮rgsm친l!

  Skriv dit sp칮rgsm친l i tekstboksen og tryk p친 'Indsend' eller Enter knappen.
feedback: |
  Benyt 游녨/游녩 til at indikere om svaret er godt eller d친rligt!
thank_you_feedback: |
  Tak for dit svar! Skriv dit sp칮rgsm친l nedenfor og tryk p친 'Indsend'.
input_box_placeholder: >
  Skriv dit sp칮rgsm친l her
submit_button_value: >
  Indsend
no_documents_reply: >
  Jeg er desv칝rre ikke i stand til at svare p친 dit sp칮rgsm친l ud fra den viden, som
  jeg har til r친dighed. Beklager!
